### PR TITLE
0.1.1 release with ParameterStore implementation

### PR DESCRIPTION
**Pull request by ulziibay**
As titled. This bumps the version so that we can release a new version.

@mcab please advise on how we can publish this as go package.

### CODE REVIEW

**Comment by mcab** [comment]
I don't believe any of our repos pulled a version of `stealth`; it's been mainly off of a commit hash:

https://github.com/Clever/ark/blob/fb70aaa56897be1797e8f4b9098dbe70d2ecf9c5/go.mod#L12
https://github.com/Clever/catapult/blob/4836d701e5a4b321df1f9d7f284f1afdeefd63ca/go.mod#L13
https://github.com/Clever/custom-cf-resources/blob/0972ecea0500cb564b3776b28366e9f044a641a2/Gopkg.toml#L7-L9

I'm also not sure how the merging of #41 ended up with a tagged version being pushed before bumping `VERSION`. It should still be pullable via other packages, we just now have a version number to pull it nicely by:

```
github.com/mcab/stealth-example via 🐹 v1.13.15 on ☁️  (us-west-1)
❯ go get github.com/Clever/stealth
go: finding github.com/Clever/stealth v0.1.0
go: downloading github.com/Clever/stealth v0.1.0
go: extracting github.com/Clever/stealth v0.1.0
```

**Comment by mcab** [comment]
...however, it does seem like it's pulling an older version of `unicreds`:

```
go: finding github.com/Clever/unicreds v1.4.0
go: downloading github.com/Clever/unicreds v1.4.0
go: extracting github.com/Clever/unicreds v1.4.0
[...]
# github.com/Clever/stealth/store
../../../../pkg/mod/github.com/!clever/stealth@v0.1.0/store/unicreds_store.go:85:74: undefined: unicreds.PaddedInt
../../../../pkg/mod/github.com/!clever/stealth@v0.1.0/store/unicreds_store.go:94:17: undefined: unicreds.GetHighestVersionSecret
../../../../pkg/mod/github.com/!clever/stealth@v0.1.0/store/unicreds_store.go:110:35: too many arguments in call to unicreds.GetSecret
../../../../pkg/mod/github.com/!clever/stealth@v0.1.0/store/unicreds_store.go:110:61: undefined: unicreds.PaddedInt
../../../../pkg/mod/github.com/!clever/stealth@v0.1.0/store/unicreds_store.go:217:23: too many arguments in call to unicreds.SetAwsConfig
	have (*string, nil, nil)
	want (*string, *string)
```

**Comment by ulziibay** [comment]
@mcab i manually tagged and released `v0.1.0` yesterday night on this repo. That way our other repos like `ark` can find the right version of this package. This is now a merely bookkeeping as there is not automated way release that pull this VERSION number

**Comment by mcab** [comment]
Since `ark` uses `go mod`, we can rreferring to the library's hash directly:

```
go get github.com/Clever/stealth@1e15dd04cd4d05f662d4f687c85558ed03eea3c4
```

Because the repo is tagged, `go mod` (and maybe `dep`, but haven't checked) will pull `0.1.0` now. This might have to be 0.1.1, so that we can add a similar line for publishing VERSION bumps: https://github.com/Clever/ark/blob/fb70aaa56897be1797e8f4b9098dbe70d2ecf9c5/.circleci/config.yml#L24.

Some modification has to happen on the CI side so that we can automagically publish, so that we don't do manual tagging of merges with version numbers.

**Review by mcab — CHANGES_REQUESTED** [review]
In https://github.com/Clever/stealth/blob/1e15dd04cd4d05f662d4f687c85558ed03eea3c4/.circleci/config.yml#L21

add the line:

https://github.com/Clever/ark/blob/fb70aaa56897be1797e8f4b9098dbe70d2ecf9c5/.circleci/config.yml#L24

and bump up the version to 0.1.1. On a successful merge to `master`, we should have the version bumped up to 0.1.1 for the repo, and properly GitHub tagged.

I added `$GH_RELEASE_TOKEN` as an environment variable in CircleCI for this project for it to work.

**Review by mcab — APPROVED** [review]

**Pull request merged**
